"""'bookings', 'users' and 'rooms' tables added

Revision ID: 6763aac2fd1d
Revises: 0dc98504f073
Create Date: 2024-06-28 23:48:25.633651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6763aac2fd1d'
down_revision: Union[str, None] = '0dc98504f073'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
